---
apiVersion: registries.wa8s.reconciler.io/v1alpha1
kind: ClusterImage
metadata:
  name: wasmtime
spec:
  image: ghcr.io/reconcilerio/wa8s/wasmtime:44.0.1@sha256:3560003ce6e930ed7d494bd90d2b2526b4c1ae0af2ef14da7dbab4724610dd1e
