---
apiVersion: registries.wa8s.reconciler.io/v1alpha1
kind: ClusterImage
metadata:
  name: wasmtime
spec:
  image: ghcr.io/componentized/wasmtime:v45.0.0@sha256:b77ac5aea9f1a54abd0891763fa7a511418b633dbb23def40413208052fe929a
