//go:build !ignore_autogenerated

/*
Copyright 2025 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentContainerImage) DeepCopyInto(out *ComponentContainerImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentContainerImage.
func (in *ComponentContainerImage) DeepCopy() *ComponentContainerImage {
	if in == nil {
		return nil
	}
	out := new(ComponentContainerImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComponentContainerImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentContainerImageList) DeepCopyInto(out *ComponentContainerImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComponentContainerImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentContainerImageList.
func (in *ComponentContainerImageList) DeepCopy() *ComponentContainerImageList {
	if in == nil {
		return nil
	}
	out := new(ComponentContainerImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComponentContainerImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentContainerImageSpec) DeepCopyInto(out *ComponentContainerImageSpec) {
	*out = *in
	out.GenericComponentSpec = in.GenericComponentSpec
	out.Ref = in.Ref
	out.ImageRef = in.ImageRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentContainerImageSpec.
func (in *ComponentContainerImageSpec) DeepCopy() *ComponentContainerImageSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentContainerImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentContainerImageStatus) DeepCopyInto(out *ComponentContainerImageStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.GenericComponentStatus.DeepCopyInto(&out.GenericComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentContainerImageStatus.
func (in *ComponentContainerImageStatus) DeepCopy() *ComponentContainerImageStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentContainerImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerDuck) DeepCopyInto(out *ContainerDuck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerDuck.
func (in *ContainerDuck) DeepCopy() *ContainerDuck {
	if in == nil {
		return nil
	}
	out := new(ContainerDuck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerDuck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerDuckList) DeepCopyInto(out *ContainerDuckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerDuck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerDuckList.
func (in *ContainerDuckList) DeepCopy() *ContainerDuckList {
	if in == nil {
		return nil
	}
	out := new(ContainerDuckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerDuckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerDuckSpec) DeepCopyInto(out *ContainerDuckSpec) {
	*out = *in
	in.GenericContainerSpec.DeepCopyInto(&out.GenericContainerSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerDuckSpec.
func (in *ContainerDuckSpec) DeepCopy() *ContainerDuckSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerDuckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerDuckStatus) DeepCopyInto(out *ContainerDuckStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.GenericContainerStatus.DeepCopyInto(&out.GenericContainerStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerDuckStatus.
func (in *ContainerDuckStatus) DeepCopy() *ContainerDuckStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerDuckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronTrigger) DeepCopyInto(out *CronTrigger) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronTrigger.
func (in *CronTrigger) DeepCopy() *CronTrigger {
	if in == nil {
		return nil
	}
	out := new(CronTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronTrigger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronTriggerList) DeepCopyInto(out *CronTriggerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CronTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronTriggerList.
func (in *CronTriggerList) DeepCopy() *CronTriggerList {
	if in == nil {
		return nil
	}
	out := new(CronTriggerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronTriggerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronTriggerSpec) DeepCopyInto(out *CronTriggerSpec) {
	*out = *in
	in.GenericContainerSpec.DeepCopyInto(&out.GenericContainerSpec)
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronTriggerSpec.
func (in *CronTriggerSpec) DeepCopy() *CronTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(CronTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronTriggerStatus) DeepCopyInto(out *CronTriggerStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.GenericContainerStatus.DeepCopyInto(&out.GenericContainerStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronTriggerStatus.
func (in *CronTriggerStatus) DeepCopy() *CronTriggerStatus {
	if in == nil {
		return nil
	}
	out := new(CronTriggerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericContainerSpec) DeepCopyInto(out *GenericContainerSpec) {
	*out = *in
	out.GenericComponentSpec = in.GenericComponentSpec
	out.Ref = in.Ref
	out.ServiceAccountRef = in.ServiceAccountRef
	in.HostCapabilities.DeepCopyInto(&out.HostCapabilities)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericContainerSpec.
func (in *GenericContainerSpec) DeepCopy() *GenericContainerSpec {
	if in == nil {
		return nil
	}
	out := new(GenericContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericContainerStatus) DeepCopyInto(out *GenericContainerStatus) {
	*out = *in
	in.GenericComponentStatus.DeepCopyInto(&out.GenericComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericContainerStatus.
func (in *GenericContainerStatus) DeepCopy() *GenericContainerStatus {
	if in == nil {
		return nil
	}
	out := new(GenericContainerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostCapabilities) DeepCopyInto(out *HostCapabilities) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = new(HostEnv)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(HostConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(HostNetwork)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostCapabilities.
func (in *HostCapabilities) DeepCopy() *HostCapabilities {
	if in == nil {
		return nil
	}
	out := new(HostCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostConfig) DeepCopyInto(out *HostConfig) {
	*out = *in
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make([]HostConfigVar, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostConfig.
func (in *HostConfig) DeepCopy() *HostConfig {
	if in == nil {
		return nil
	}
	out := new(HostConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostConfigVar) DeepCopyInto(out *HostConfigVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostConfigVar.
func (in *HostConfigVar) DeepCopy() *HostConfigVar {
	if in == nil {
		return nil
	}
	out := new(HostConfigVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostEnv) DeepCopyInto(out *HostEnv) {
	*out = *in
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make([]HostEnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostEnv.
func (in *HostEnv) DeepCopy() *HostEnv {
	if in == nil {
		return nil
	}
	out := new(HostEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostEnvVar) DeepCopyInto(out *HostEnvVar) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostEnvVar.
func (in *HostEnvVar) DeepCopy() *HostEnvVar {
	if in == nil {
		return nil
	}
	out := new(HostEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostNetwork) DeepCopyInto(out *HostNetwork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostNetwork.
func (in *HostNetwork) DeepCopy() *HostNetwork {
	if in == nil {
		return nil
	}
	out := new(HostNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpTrigger) DeepCopyInto(out *HttpTrigger) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpTrigger.
func (in *HttpTrigger) DeepCopy() *HttpTrigger {
	if in == nil {
		return nil
	}
	out := new(HttpTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HttpTrigger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpTriggerList) DeepCopyInto(out *HttpTriggerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HttpTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpTriggerList.
func (in *HttpTriggerList) DeepCopy() *HttpTriggerList {
	if in == nil {
		return nil
	}
	out := new(HttpTriggerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HttpTriggerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpTriggerSpec) DeepCopyInto(out *HttpTriggerSpec) {
	*out = *in
	in.GenericContainerSpec.DeepCopyInto(&out.GenericContainerSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpTriggerSpec.
func (in *HttpTriggerSpec) DeepCopy() *HttpTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(HttpTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpTriggerStatus) DeepCopyInto(out *HttpTriggerStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.GenericContainerStatus.DeepCopyInto(&out.GenericContainerStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpTriggerStatus.
func (in *HttpTriggerStatus) DeepCopy() *HttpTriggerStatus {
	if in == nil {
		return nil
	}
	out := new(HttpTriggerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WIT) DeepCopyInto(out *WIT) {
	*out = *in
	if in.Imports != nil {
		in, out := &in.Imports, &out.Imports
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WIT.
func (in *WIT) DeepCopy() *WIT {
	if in == nil {
		return nil
	}
	out := new(WIT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WrpcTrigger) DeepCopyInto(out *WrpcTrigger) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WrpcTrigger.
func (in *WrpcTrigger) DeepCopy() *WrpcTrigger {
	if in == nil {
		return nil
	}
	out := new(WrpcTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WrpcTrigger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WrpcTriggerList) DeepCopyInto(out *WrpcTriggerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WrpcTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WrpcTriggerList.
func (in *WrpcTriggerList) DeepCopy() *WrpcTriggerList {
	if in == nil {
		return nil
	}
	out := new(WrpcTriggerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WrpcTriggerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WrpcTriggerSpec) DeepCopyInto(out *WrpcTriggerSpec) {
	*out = *in
	in.GenericContainerSpec.DeepCopyInto(&out.GenericContainerSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WrpcTriggerSpec.
func (in *WrpcTriggerSpec) DeepCopy() *WrpcTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(WrpcTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WrpcTriggerStatus) DeepCopyInto(out *WrpcTriggerStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.GenericContainerStatus.DeepCopyInto(&out.GenericContainerStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WrpcTriggerStatus.
func (in *WrpcTriggerStatus) DeepCopy() *WrpcTriggerStatus {
	if in == nil {
		return nil
	}
	out := new(WrpcTriggerStatus)
	in.DeepCopyInto(out)
	return out
}
