---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-registries-wa8s-reconciler-io-v1alpha1-clusterrepository
  failurePolicy: Fail
  name: v1alpha1.clusterrepositories.registries.wa8s.reconciler.io
  rules:
  - apiGroups:
    - registries.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterrepositories
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-registries-wa8s-reconciler-io-v1alpha1-repository
  failurePolicy: Fail
  name: v1alpha1.repositories.registries.wa8s.reconciler.io
  rules:
  - apiGroups:
    - registries.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-wa8s-reconciler-io-v1alpha1-clustercomponent
  failurePolicy: Fail
  name: v1alpha1.clustercomponents.wa8s.reconciler.io
  rules:
  - apiGroups:
    - wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustercomponents
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-wa8s-reconciler-io-v1alpha1-component
  failurePolicy: Fail
  name: v1alpha1.components.wa8s.reconciler.io
  rules:
  - apiGroups:
    - wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - components
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-wa8s-reconciler-io-v1alpha1-composition
  failurePolicy: Fail
  name: v1alpha1.compositions.wa8s.reconciler.io
  rules:
  - apiGroups:
    - wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - compositions
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-wa8s-reconciler-io-v1alpha1-configstore
  failurePolicy: Fail
  name: v1alpha1.configstores.wa8s.reconciler.io
  rules:
  - apiGroups:
    - wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configstores
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-containers-wa8s-reconciler-io-v1alpha1-crontrigger
  failurePolicy: Fail
  name: v1alpha1.crontriggers.containers.wa8s.reconciler.io
  rules:
  - apiGroups:
    - containers.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - crontriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-containers-wa8s-reconciler-io-v1alpha1-httptrigger
  failurePolicy: Fail
  name: v1alpha1.httptriggers.containers.wa8s.reconciler.io
  rules:
  - apiGroups:
    - containers.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httptriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-containers-wa8s-reconciler-io-v1alpha1-wasmtimecontainer
  failurePolicy: Fail
  name: v1alpha1.wasmtimecontainers.containers.wa8s.reconciler.io
  rules:
  - apiGroups:
    - containers.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - wasmtimecontainers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-containers-wa8s-reconciler-io-v1alpha1-wrpctrigger
  failurePolicy: Fail
  name: v1alpha1.wrpctriggers.containers.wa8s.reconciler.io
  rules:
  - apiGroups:
    - containers.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - wrpctriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-clusterservicelifecycle
  failurePolicy: Fail
  name: v1alpha1.clusterservicelifecycles.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterservicelifecycles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-servicebinding
  failurePolicy: Fail
  name: v1alpha1.servicebindings.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicebindings
    - servicebindings/status
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-serviceclient
  failurePolicy: Fail
  name: v1alpha1.serviceclients.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceclients
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-serviceinstance
  failurePolicy: Fail
  name: v1alpha1.serviceinstances.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceinstances
    - serviceinstances/status
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-servicelifecycle
  failurePolicy: Fail
  name: v1alpha1.servicelifecycles.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicelifecycles
  sideEffects: None
