---
apiVersion: registries.wa8s.reconciler.io/v1alpha1
kind: ClusterRepository
metadata:
  name: default
spec:
  template: registry.wa8s-system.svc.cluster.local/{{ .Kind }}/{{ .UID }}:{{ .ResourceVersion }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-cert
spec:
  # $(SERVICE_NAME) and $(NAMESPACE) will be substituted by kustomize
  dnsNames:
  - $(SERVICE_NAME).$(NAMESPACE).svc
  - $(SERVICE_NAME).$(NAMESPACE).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: registry-cert

---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:8443
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: registry-cert
          readOnly: true
          mountPath: "/certs"
        - name: registry-data
          mountPath: /var/lib/registry
      volumes:
      - name: registry-cert
        secret:
          secretName: registry-cert
      - name: registry-data
        # TODO use something more durable
        emptyDir: {}
