---
apiVersion: containers.wa8s.reconciler.io/v1alpha1
kind: HttpTrigger
metadata:
  name: incrementor
spec:
  ref:
    name: http-incrementor
  hostCapabilities:
    network:
      inherit: true
      ipNameLookup: true

---
apiVersion: wa8s.reconciler.io/v1alpha1
kind: Composition
metadata:
  name: http-incrementor
spec:
  dependencies:
  - component: componentized:http-incrementor
    oci:
      image: ghcr.io/componentized/valkey/sample-http-incrementor:v0.2.1@sha256:9c7c7f02cfa044212b8aa335f0dfcc52041d4377fabcc8f86e233be49d395c9e
  - component: componentized:valkey-client
    ref:
      apiVersion: x.services.wa8s.reconciler.io/v1alpha1
      kind: ValkeyClient
      name: my-valkey
  - component: componentized:logging
    ref:
      kind: ClusterComponent
      name: wa8s-services-logging
