//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1alpha1

import (
	testingx "testing"

	testing "reconciler.io/dies/testing"
)

func TestServiceBindingSpecDie_MissingMethods(t *testingx.T) {
	die := ServiceBindingSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceBindingSpecDie: %s", diff.List())
	}
}

func TestServiceBindingStatusDie_MissingMethods(t *testingx.T) {
	die := ServiceBindingStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceBindingStatusDie: %s", diff.List())
	}
}

func TestServiceBindingDie_MissingMethods(t *testingx.T) {
	die := ServiceBindingBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceBindingDie: %s", diff.List())
	}
}

func TestServiceClientSpecDie_MissingMethods(t *testingx.T) {
	die := ServiceClientSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceClientSpecDie: %s", diff.List())
	}
}

func TestServiceClientStatusDie_MissingMethods(t *testingx.T) {
	die := ServiceClientStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceClientStatusDie: %s", diff.List())
	}
}

func TestServiceClientDie_MissingMethods(t *testingx.T) {
	die := ServiceClientBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceClientDie: %s", diff.List())
	}
}

func TestServiceInstanceReferenceDie_MissingMethods(t *testingx.T) {
	die := ServiceInstanceReferenceBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceInstanceReferenceDie: %s", diff.List())
	}
}

func TestServiceInstanceSpecDie_MissingMethods(t *testingx.T) {
	die := ServiceInstanceSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceInstanceSpecDie: %s", diff.List())
	}
}

func TestServiceInstanceRequestDie_MissingMethods(t *testingx.T) {
	die := ServiceInstanceRequestBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceInstanceRequestDie: %s", diff.List())
	}
}

func TestServiceInstanceStatusDie_MissingMethods(t *testingx.T) {
	die := ServiceInstanceStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceInstanceStatusDie: %s", diff.List())
	}
}

func TestServiceInstanceDie_MissingMethods(t *testingx.T) {
	die := ServiceInstanceBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceInstanceDie: %s", diff.List())
	}
}

func TestServiceLifecycleReferenceDie_MissingMethods(t *testingx.T) {
	die := ServiceLifecycleReferenceBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceLifecycleReferenceDie: %s", diff.List())
	}
}

func TestServiceLifecycleSpecDie_MissingMethods(t *testingx.T) {
	die := ServiceLifecycleSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceLifecycleSpecDie: %s", diff.List())
	}
}

func TestServiceLifecycleStatusDie_MissingMethods(t *testingx.T) {
	die := ServiceLifecycleStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceLifecycleStatusDie: %s", diff.List())
	}
}

func TestServiceLifecycleDie_MissingMethods(t *testingx.T) {
	die := ServiceLifecycleBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceLifecycleDie: %s", diff.List())
	}
}

func TestClusterServiceLifecycleDie_MissingMethods(t *testingx.T) {
	die := ClusterServiceLifecycleBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ClusterServiceLifecycleDie: %s", diff.List())
	}
}
