---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: wa8s-services-manager-webhook
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-clusterservicelifecycle
  failurePolicy: Fail
  name: v1alpha1.clusterservicelifecycles.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterservicelifecycles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: wa8s-services-manager-webhook
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-servicebinding
  failurePolicy: Fail
  name: v1alpha1.servicebindings.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicebindings
    - servicebindings/status
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: wa8s-services-manager-webhook
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-serviceclient
  failurePolicy: Fail
  name: v1alpha1.serviceclients.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceclients
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: wa8s-services-manager-webhook
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-serviceinstance
  failurePolicy: Fail
  name: v1alpha1.serviceinstances.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceinstances
    - serviceinstances/status
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: wa8s-services-manager-webhook
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-servicelifecycle
  failurePolicy: Fail
  name: v1alpha1.servicelifecycles.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicelifecycles
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: wa8s-services-manager-webhook
      namespace: system
      path: /validate-services-wa8s-reconciler-io-v1alpha1-serviceresourcedefinition
  failurePolicy: Fail
  name: v1alpha1.serviceresourcedefinitions.services.wa8s.reconciler.io
  rules:
  - apiGroups:
    - services.wa8s.reconciler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceresourcedefinitions
  sideEffects: None
