apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wa8s
    app.kubernetes.io/managed-by: kustomize
  name: wa8s-manager-aggregate-role
aggregationRule:
  clusterRoleSelectors:
  - matchExpressions:
    - key: wa8s.reconciler.io/manager
      operator: Exists
rules: [] # The control plane automatically fills in the rules

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: wa8s
    app.kubernetes.io/managed-by: kustomize
  name: wa8s-manager-aggregate-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wa8s-manager-aggregate-role
subjects:
- kind: ServiceAccount
  name: controller-manager
