apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
- path: [rules]
  type: copy
  sources: [existing]
  resourceMatchers:
  - andMatcher:
      matchers:
      - apiVersionKindMatcher: {apiVersion: rbac.authorization.k8s.io/v1, kind: ClusterRole}
      - notMatcher:
          matcher:
            emptyFieldMatcher:
              path: [aggregationRule]
waitRules:
- supportsObservedGeneration: true
  conditionMatchers:
  - type: Ready
    status: "True"
    success: true
  resourceMatchers:
  - anyMatcher:
    matchers:
    - apiGroupKindMatcher: {apiGroup: wa8s.reconciler.io, kind: ClusterComponent}
    - apiGroupKindMatcher: {apiGroup: wa8s.reconciler.io, kind: Component}
    - apiGroupKindMatcher: {apiGroup: wa8s.reconciler.io, kind: Composition}
    - apiGroupKindMatcher: {apiGroup: wa8s.reconciler.io, kind: ConfigStore}
    - apiGroupKindMatcher: {apiGroup: containers.wa8s.reconciler.io, kind: CronTrigger}
    - apiGroupKindMatcher: {apiGroup: containers.wa8s.reconciler.io, kind: HttpTrigger}
    - apiGroupKindMatcher: {apiGroup: containers.wa8s.reconciler.io, kind: WasmtimeContainer}
    - apiGroupKindMatcher: {apiGroup: containers.wa8s.reconciler.io, kind: WrpcTrigger}
    - apiGroupKindMatcher: {apiGroup: duck.wa8s.reconciler.io, kind: ComponentDuck}
    - apiGroupKindMatcher: {apiGroup: registries.wa8s.reconciler.io, kind: ClusterRepository}
    - apiGroupKindMatcher: {apiGroup: registries.wa8s.reconciler.io, kind: Repository}
    - apiGroupKindMatcher: {apiGroup: services.wa8s.reconciler.io, kind: ClusterServiceLifecycle}
    - apiGroupKindMatcher: {apiGroup: services.wa8s.reconciler.io, kind: ServiceBinding}
    - apiGroupKindMatcher: {apiGroup: services.wa8s.reconciler.io, kind: ServiceClient}
    - apiGroupKindMatcher: {apiGroup: services.wa8s.reconciler.io, kind: ServiceInstance}
    - apiGroupKindMatcher: {apiGroup: services.wa8s.reconciler.io, kind: ServiceLifecycle}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kapp.k14s.io/exists: ""
  name: componentducks.duck.wa8s.reconciler.io
spec:
  group: duck.wa8s.reconciler.io
  versions:
  - name: v1
  names:
    kind: ComponentDuck
