//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1alpha1

import (
	fmtx "fmt"
	osx "os"
	reflectx "reflect"

	cmp "github.com/google/go-cmp/cmp"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	json "k8s.io/apimachinery/pkg/util/json"
	jsonpath "k8s.io/client-go/util/jsonpath"
	metav1 "reconciler.io/dies/apis/meta/v1"
	patch "reconciler.io/dies/patch"
	"reconciler.io/runtime/apis"
	yaml "sigs.k8s.io/yaml"

	containersv1alpha1 "reconciler.io/wa8s/apis/containers/v1alpha1"
	v1 "reconciler.io/wa8s/integrations/knative/apis/serving/v1"
)

var ServiceTriggerSpecBlank = (&ServiceTriggerSpecDie{}).DieFeed(ServiceTriggerSpec{})

type ServiceTriggerSpecDie struct {
	mutable bool
	r       ServiceTriggerSpec
	seal    ServiceTriggerSpec
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ServiceTriggerSpecDie) DieImmutable(immutable bool) *ServiceTriggerSpecDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ServiceTriggerSpecDie) DieFeed(r ServiceTriggerSpec) *ServiceTriggerSpecDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ServiceTriggerSpecDie{
		mutable: d.mutable,
		r:       r,
		seal:    d.seal,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ServiceTriggerSpecDie) DieFeedPtr(r *ServiceTriggerSpec) *ServiceTriggerSpecDie {
	if r == nil {
		r = &ServiceTriggerSpec{}
	}
	return d.DieFeed(*r)
}

// DieFeedDuck returns a new die with the provided value converted into the underlying type. Panics on error.
func (d *ServiceTriggerSpecDie) DieFeedDuck(v any) *ServiceTriggerSpecDie {
	data, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(data)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ServiceTriggerSpecDie) DieFeedJSON(j []byte) *ServiceTriggerSpecDie {
	r := ServiceTriggerSpec{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ServiceTriggerSpecDie) DieFeedYAML(y []byte) *ServiceTriggerSpecDie {
	r := ServiceTriggerSpec{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ServiceTriggerSpecDie) DieFeedYAMLFile(name string) *ServiceTriggerSpecDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ServiceTriggerSpecDie) DieFeedRawExtension(raw runtime.RawExtension) *ServiceTriggerSpecDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ServiceTriggerSpecDie) DieRelease() ServiceTriggerSpec {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ServiceTriggerSpecDie) DieReleasePtr() *ServiceTriggerSpec {
	r := d.DieRelease()
	return &r
}

// DieReleaseDuck releases the value into the passed value and returns the same. Panics on error.
func (d *ServiceTriggerSpecDie) DieReleaseDuck(v any) any {
	data := d.DieReleaseJSON()
	if err := json.Unmarshal(data, v); err != nil {
		panic(err)
	}
	return v
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ServiceTriggerSpecDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ServiceTriggerSpecDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ServiceTriggerSpecDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ServiceTriggerSpecDie) DieStamp(fn func(r *ServiceTriggerSpec)) *ServiceTriggerSpecDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ServiceTriggerSpecDie) DieStampAt(jp string, fn interface{}) *ServiceTriggerSpecDie {
	return d.DieStamp(func(r *ServiceTriggerSpec) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *ServiceTriggerSpecDie) DieWith(fns ...func(d *ServiceTriggerSpecDie)) *ServiceTriggerSpecDie {
	nd := ServiceTriggerSpecBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ServiceTriggerSpecDie) DeepCopy() *ServiceTriggerSpecDie {
	r := *d.r.DeepCopy()
	return &ServiceTriggerSpecDie{
		mutable: d.mutable,
		r:       r,
		seal:    d.seal,
	}
}

// DieSeal returns a new die for the current die's state that is sealed for comparison in future diff and patch operations.
func (d *ServiceTriggerSpecDie) DieSeal() *ServiceTriggerSpecDie {
	return d.DieSealFeed(d.r)
}

// DieSealFeed returns a new die for the current die's state that uses a specific resource for comparison in future diff and patch operations.
func (d *ServiceTriggerSpecDie) DieSealFeed(r ServiceTriggerSpec) *ServiceTriggerSpecDie {
	if !d.mutable {
		d = d.DeepCopy()
	}
	d.seal = *r.DeepCopy()
	return d
}

// DieSealFeedPtr returns a new die for the current die's state that uses a specific resource pointer for comparison in future diff and patch operations. If the resource is nil, the empty value is used instead.
func (d *ServiceTriggerSpecDie) DieSealFeedPtr(r *ServiceTriggerSpec) *ServiceTriggerSpecDie {
	if r == nil {
		r = &ServiceTriggerSpec{}
	}
	return d.DieSealFeed(*r)
}

// DieSealRelease returns the sealed resource managed by the die.
func (d *ServiceTriggerSpecDie) DieSealRelease() ServiceTriggerSpec {
	return *d.seal.DeepCopy()
}

// DieSealReleasePtr returns the sealed resource pointer managed by the die.
func (d *ServiceTriggerSpecDie) DieSealReleasePtr() *ServiceTriggerSpec {
	r := d.DieSealRelease()
	return &r
}

// DieDiff uses cmp.Diff to compare the current value of the die with the sealed value.
func (d *ServiceTriggerSpecDie) DieDiff(opts ...cmp.Option) string {
	return cmp.Diff(d.seal, d.r, opts...)
}

// DiePatch generates a patch between the current value of the die and the sealed value.
func (d *ServiceTriggerSpecDie) DiePatch(patchType types.PatchType) ([]byte, error) {
	return patch.Create(d.seal, d.r, patchType)
}

// GenericContainerSpecDie mutates GenericContainerSpec as a die.
func (d *ServiceTriggerSpecDie) GenericContainerSpecDie(fn func(d *containersv1alpha1.GenericContainerSpecDie)) *ServiceTriggerSpecDie {
	return d.DieStamp(func(r *ServiceTriggerSpec) {
		d := containersv1alpha1.GenericContainerSpecBlank.DieImmutable(false).DieFeed(r.GenericContainerSpec)
		fn(d)
		r.GenericContainerSpec = d.DieRelease()
	})
}

// ConfigurationSpecDie mutates ConfigurationSpec as a die.
//
// ServiceSpec inlines an unrestricted ConfigurationSpec.
func (d *ServiceTriggerSpecDie) ConfigurationSpecDie(fn func(d *v1.ConfigurationSpecDie)) *ServiceTriggerSpecDie {
	return d.DieStamp(func(r *ServiceTriggerSpec) {
		d := v1.ConfigurationSpecBlank.DieImmutable(false).DieFeed(r.ConfigurationSpec)
		fn(d)
		r.ConfigurationSpec = d.DieRelease()
	})
}

// RouteSpecDie mutates RouteSpec as a die.
//
// ServiceSpec inlines RouteSpec and restricts/defaults its fields
//
// via webhook.  In particular, this spec can only reference this
//
// # Service's configuration and revisions (which also influences
//
// defaults).
func (d *ServiceTriggerSpecDie) RouteSpecDie(fn func(d *v1.RouteSpecDie)) *ServiceTriggerSpecDie {
	return d.DieStamp(func(r *ServiceTriggerSpec) {
		d := v1.RouteSpecBlank.DieImmutable(false).DieFeed(r.RouteSpec)
		fn(d)
		r.RouteSpec = d.DieRelease()
	})
}

func (d *ServiceTriggerSpecDie) GenericContainerSpec(v containersv1alpha1.GenericContainerSpec) *ServiceTriggerSpecDie {
	return d.DieStamp(func(r *ServiceTriggerSpec) {
		r.GenericContainerSpec = v
	})
}

// ServiceSpec inlines an unrestricted ConfigurationSpec.
func (d *ServiceTriggerSpecDie) ConfigurationSpec(v v1.ConfigurationSpec) *ServiceTriggerSpecDie {
	return d.DieStamp(func(r *ServiceTriggerSpec) {
		r.ConfigurationSpec = v
	})
}

// ServiceSpec inlines RouteSpec and restricts/defaults its fields
//
// via webhook.  In particular, this spec can only reference this
//
// # Service's configuration and revisions (which also influences
//
// defaults).
func (d *ServiceTriggerSpecDie) RouteSpec(v v1.RouteSpec) *ServiceTriggerSpecDie {
	return d.DieStamp(func(r *ServiceTriggerSpec) {
		r.RouteSpec = v
	})
}

var ServiceTriggerStatusBlank = (&ServiceTriggerStatusDie{}).DieFeed(ServiceTriggerStatus{})

type ServiceTriggerStatusDie struct {
	mutable bool
	r       ServiceTriggerStatus
	seal    ServiceTriggerStatus
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ServiceTriggerStatusDie) DieImmutable(immutable bool) *ServiceTriggerStatusDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ServiceTriggerStatusDie) DieFeed(r ServiceTriggerStatus) *ServiceTriggerStatusDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ServiceTriggerStatusDie{
		mutable: d.mutable,
		r:       r,
		seal:    d.seal,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ServiceTriggerStatusDie) DieFeedPtr(r *ServiceTriggerStatus) *ServiceTriggerStatusDie {
	if r == nil {
		r = &ServiceTriggerStatus{}
	}
	return d.DieFeed(*r)
}

// DieFeedDuck returns a new die with the provided value converted into the underlying type. Panics on error.
func (d *ServiceTriggerStatusDie) DieFeedDuck(v any) *ServiceTriggerStatusDie {
	data, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(data)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ServiceTriggerStatusDie) DieFeedJSON(j []byte) *ServiceTriggerStatusDie {
	r := ServiceTriggerStatus{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ServiceTriggerStatusDie) DieFeedYAML(y []byte) *ServiceTriggerStatusDie {
	r := ServiceTriggerStatus{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ServiceTriggerStatusDie) DieFeedYAMLFile(name string) *ServiceTriggerStatusDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ServiceTriggerStatusDie) DieFeedRawExtension(raw runtime.RawExtension) *ServiceTriggerStatusDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ServiceTriggerStatusDie) DieRelease() ServiceTriggerStatus {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ServiceTriggerStatusDie) DieReleasePtr() *ServiceTriggerStatus {
	r := d.DieRelease()
	return &r
}

// DieReleaseDuck releases the value into the passed value and returns the same. Panics on error.
func (d *ServiceTriggerStatusDie) DieReleaseDuck(v any) any {
	data := d.DieReleaseJSON()
	if err := json.Unmarshal(data, v); err != nil {
		panic(err)
	}
	return v
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ServiceTriggerStatusDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ServiceTriggerStatusDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ServiceTriggerStatusDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ServiceTriggerStatusDie) DieStamp(fn func(r *ServiceTriggerStatus)) *ServiceTriggerStatusDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ServiceTriggerStatusDie) DieStampAt(jp string, fn interface{}) *ServiceTriggerStatusDie {
	return d.DieStamp(func(r *ServiceTriggerStatus) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *ServiceTriggerStatusDie) DieWith(fns ...func(d *ServiceTriggerStatusDie)) *ServiceTriggerStatusDie {
	nd := ServiceTriggerStatusBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ServiceTriggerStatusDie) DeepCopy() *ServiceTriggerStatusDie {
	r := *d.r.DeepCopy()
	return &ServiceTriggerStatusDie{
		mutable: d.mutable,
		r:       r,
		seal:    d.seal,
	}
}

// DieSeal returns a new die for the current die's state that is sealed for comparison in future diff and patch operations.
func (d *ServiceTriggerStatusDie) DieSeal() *ServiceTriggerStatusDie {
	return d.DieSealFeed(d.r)
}

// DieSealFeed returns a new die for the current die's state that uses a specific resource for comparison in future diff and patch operations.
func (d *ServiceTriggerStatusDie) DieSealFeed(r ServiceTriggerStatus) *ServiceTriggerStatusDie {
	if !d.mutable {
		d = d.DeepCopy()
	}
	d.seal = *r.DeepCopy()
	return d
}

// DieSealFeedPtr returns a new die for the current die's state that uses a specific resource pointer for comparison in future diff and patch operations. If the resource is nil, the empty value is used instead.
func (d *ServiceTriggerStatusDie) DieSealFeedPtr(r *ServiceTriggerStatus) *ServiceTriggerStatusDie {
	if r == nil {
		r = &ServiceTriggerStatus{}
	}
	return d.DieSealFeed(*r)
}

// DieSealRelease returns the sealed resource managed by the die.
func (d *ServiceTriggerStatusDie) DieSealRelease() ServiceTriggerStatus {
	return *d.seal.DeepCopy()
}

// DieSealReleasePtr returns the sealed resource pointer managed by the die.
func (d *ServiceTriggerStatusDie) DieSealReleasePtr() *ServiceTriggerStatus {
	r := d.DieSealRelease()
	return &r
}

// DieDiff uses cmp.Diff to compare the current value of the die with the sealed value.
func (d *ServiceTriggerStatusDie) DieDiff(opts ...cmp.Option) string {
	return cmp.Diff(d.seal, d.r, opts...)
}

// DiePatch generates a patch between the current value of the die and the sealed value.
func (d *ServiceTriggerStatusDie) DiePatch(patchType types.PatchType) ([]byte, error) {
	return patch.Create(d.seal, d.r, patchType)
}

// GenericContainerStatusDie mutates GenericContainerStatus as a die.
func (d *ServiceTriggerStatusDie) GenericContainerStatusDie(fn func(d *containersv1alpha1.GenericContainerStatusDie)) *ServiceTriggerStatusDie {
	return d.DieStamp(func(r *ServiceTriggerStatus) {
		d := containersv1alpha1.GenericContainerStatusBlank.DieImmutable(false).DieFeed(r.GenericContainerStatus)
		fn(d)
		r.GenericContainerStatus = d.DieRelease()
	})
}

// ConfigurationStatusFieldsDie mutates ConfigurationStatusFields as a die.
//
// # In addition to inlining ConfigurationSpec, we also inline the fields
//
// specific to ConfigurationStatus.
func (d *ServiceTriggerStatusDie) ConfigurationStatusFieldsDie(fn func(d *v1.ConfigurationStatusFieldsDie)) *ServiceTriggerStatusDie {
	return d.DieStamp(func(r *ServiceTriggerStatus) {
		d := v1.ConfigurationStatusFieldsBlank.DieImmutable(false).DieFeed(r.ConfigurationStatusFields)
		fn(d)
		r.ConfigurationStatusFields = d.DieRelease()
	})
}

// RouteStatusFieldsDie mutates RouteStatusFields as a die.
//
// # In addition to inlining RouteSpec, we also inline the fields
//
// specific to RouteStatus.
func (d *ServiceTriggerStatusDie) RouteStatusFieldsDie(fn func(d *v1.RouteStatusFieldsDie)) *ServiceTriggerStatusDie {
	return d.DieStamp(func(r *ServiceTriggerStatus) {
		d := v1.RouteStatusFieldsBlank.DieImmutable(false).DieFeed(r.RouteStatusFields)
		fn(d)
		r.RouteStatusFields = d.DieRelease()
	})
}

func (d *ServiceTriggerStatusDie) Status(v apis.Status) *ServiceTriggerStatusDie {
	return d.DieStamp(func(r *ServiceTriggerStatus) {
		r.Status = v
	})
}

func (d *ServiceTriggerStatusDie) GenericContainerStatus(v containersv1alpha1.GenericContainerStatus) *ServiceTriggerStatusDie {
	return d.DieStamp(func(r *ServiceTriggerStatus) {
		r.GenericContainerStatus = v
	})
}

// Annotations is additional Status fields for the Resource to save some
//
// additional State as well as convey more information to the user. This is
//
// roughly akin to Annotations on any k8s resource, just the reconciler conveying
//
// richer information outwards.
func (d *ServiceTriggerStatusDie) Annotations(v map[string]string) *ServiceTriggerStatusDie {
	return d.DieStamp(func(r *ServiceTriggerStatus) {
		r.Annotations = v
	})
}

// In addition to inlining ConfigurationSpec, we also inline the fields
//
// specific to ConfigurationStatus.
func (d *ServiceTriggerStatusDie) ConfigurationStatusFields(v v1.ConfigurationStatusFields) *ServiceTriggerStatusDie {
	return d.DieStamp(func(r *ServiceTriggerStatus) {
		r.ConfigurationStatusFields = v
	})
}

// In addition to inlining RouteSpec, we also inline the fields
//
// specific to RouteStatus.
func (d *ServiceTriggerStatusDie) RouteStatusFields(v v1.RouteStatusFields) *ServiceTriggerStatusDie {
	return d.DieStamp(func(r *ServiceTriggerStatus) {
		r.RouteStatusFields = v
	})
}

var ServiceTriggerBlank = (&ServiceTriggerDie{}).DieFeed(ServiceTrigger{})

type ServiceTriggerDie struct {
	metav1.FrozenObjectMeta
	mutable bool
	r       ServiceTrigger
	seal    ServiceTrigger
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ServiceTriggerDie) DieImmutable(immutable bool) *ServiceTriggerDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ServiceTriggerDie) DieFeed(r ServiceTrigger) *ServiceTriggerDie {
	if d.mutable {
		d.FrozenObjectMeta = metav1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &ServiceTriggerDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
		seal:             d.seal,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ServiceTriggerDie) DieFeedPtr(r *ServiceTrigger) *ServiceTriggerDie {
	if r == nil {
		r = &ServiceTrigger{}
	}
	return d.DieFeed(*r)
}

// DieFeedDuck returns a new die with the provided value converted into the underlying type. Panics on error.
func (d *ServiceTriggerDie) DieFeedDuck(v any) *ServiceTriggerDie {
	data, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(data)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ServiceTriggerDie) DieFeedJSON(j []byte) *ServiceTriggerDie {
	r := ServiceTrigger{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ServiceTriggerDie) DieFeedYAML(y []byte) *ServiceTriggerDie {
	r := ServiceTrigger{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ServiceTriggerDie) DieFeedYAMLFile(name string) *ServiceTriggerDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ServiceTriggerDie) DieFeedRawExtension(raw runtime.RawExtension) *ServiceTriggerDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ServiceTriggerDie) DieRelease() ServiceTrigger {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ServiceTriggerDie) DieReleasePtr() *ServiceTrigger {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object. Panics on error.
func (d *ServiceTriggerDie) DieReleaseUnstructured() *unstructured.Unstructured {
	r := d.DieReleasePtr()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	if err != nil {
		panic(err)
	}
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieReleaseDuck releases the value into the passed value and returns the same. Panics on error.
func (d *ServiceTriggerDie) DieReleaseDuck(v any) any {
	data := d.DieReleaseJSON()
	if err := json.Unmarshal(data, v); err != nil {
		panic(err)
	}
	return v
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ServiceTriggerDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ServiceTriggerDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ServiceTriggerDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ServiceTriggerDie) DieStamp(fn func(r *ServiceTrigger)) *ServiceTriggerDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ServiceTriggerDie) DieStampAt(jp string, fn interface{}) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *ServiceTriggerDie) DieWith(fns ...func(d *ServiceTriggerDie)) *ServiceTriggerDie {
	nd := ServiceTriggerBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ServiceTriggerDie) DeepCopy() *ServiceTriggerDie {
	r := *d.r.DeepCopy()
	return &ServiceTriggerDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
		seal:             d.seal,
	}
}

// DieSeal returns a new die for the current die's state that is sealed for comparison in future diff and patch operations.
func (d *ServiceTriggerDie) DieSeal() *ServiceTriggerDie {
	return d.DieSealFeed(d.r)
}

// DieSealFeed returns a new die for the current die's state that uses a specific resource for comparison in future diff and patch operations.
func (d *ServiceTriggerDie) DieSealFeed(r ServiceTrigger) *ServiceTriggerDie {
	if !d.mutable {
		d = d.DeepCopy()
	}
	d.seal = *r.DeepCopy()
	return d
}

// DieSealFeedPtr returns a new die for the current die's state that uses a specific resource pointer for comparison in future diff and patch operations. If the resource is nil, the empty value is used instead.
func (d *ServiceTriggerDie) DieSealFeedPtr(r *ServiceTrigger) *ServiceTriggerDie {
	if r == nil {
		r = &ServiceTrigger{}
	}
	return d.DieSealFeed(*r)
}

// DieSealRelease returns the sealed resource managed by the die.
func (d *ServiceTriggerDie) DieSealRelease() ServiceTrigger {
	return *d.seal.DeepCopy()
}

// DieSealReleasePtr returns the sealed resource pointer managed by the die.
func (d *ServiceTriggerDie) DieSealReleasePtr() *ServiceTrigger {
	r := d.DieSealRelease()
	return &r
}

// DieDiff uses cmp.Diff to compare the current value of the die with the sealed value.
func (d *ServiceTriggerDie) DieDiff(opts ...cmp.Option) string {
	return cmp.Diff(d.seal, d.r, opts...)
}

// DiePatch generates a patch between the current value of the die and the sealed value.
func (d *ServiceTriggerDie) DiePatch(patchType types.PatchType) ([]byte, error) {
	return patch.Create(d.seal, d.r, patchType)
}

var _ runtime.Object = (*ServiceTriggerDie)(nil)

func (d *ServiceTriggerDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *ServiceTriggerDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *ServiceTriggerDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *ServiceTriggerDie) UnmarshalJSON(b []byte) error {
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	resource := &ServiceTrigger{}
	err := json.Unmarshal(b, resource)
	*d = *d.DieFeed(*resource)
	return err
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (d *ServiceTriggerDie) APIVersion(v string) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		r.APIVersion = v
	})
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (d *ServiceTriggerDie) Kind(v string) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		r.Kind = v
	})
}

// TypeMetadata standard object's type metadata.
func (d *ServiceTriggerDie) TypeMetadata(v apismetav1.TypeMeta) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		r.TypeMeta = v
	})
}

// TypeMetadataDie stamps the resource's TypeMeta field with a mutable die.
func (d *ServiceTriggerDie) TypeMetadataDie(fn func(d *metav1.TypeMetaDie)) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		d := metav1.TypeMetaBlank.DieImmutable(false).DieFeed(r.TypeMeta)
		fn(d)
		r.TypeMeta = d.DieRelease()
	})
}

// Metadata standard object's metadata.
func (d *ServiceTriggerDie) Metadata(v apismetav1.ObjectMeta) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		r.ObjectMeta = v
	})
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *ServiceTriggerDie) MetadataDie(fn func(d *metav1.ObjectMetaDie)) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		d := metav1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// SpecDie stamps the resource's spec field with a mutable die.
func (d *ServiceTriggerDie) SpecDie(fn func(d *ServiceTriggerSpecDie)) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		d := ServiceTriggerSpecBlank.DieImmutable(false).DieFeed(r.Spec)
		fn(d)
		r.Spec = d.DieRelease()
	})
}

// StatusDie stamps the resource's status field with a mutable die.
func (d *ServiceTriggerDie) StatusDie(fn func(d *ServiceTriggerStatusDie)) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		d := ServiceTriggerStatusBlank.DieImmutable(false).DieFeed(r.Status)
		fn(d)
		r.Status = d.DieRelease()
	})
}

func (d *ServiceTriggerDie) Spec(v ServiceTriggerSpec) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		r.Spec = v
	})
}

func (d *ServiceTriggerDie) Status(v ServiceTriggerStatus) *ServiceTriggerDie {
	return d.DieStamp(func(r *ServiceTrigger) {
		r.Status = v
	})
}
