//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1

import (
	testingx "testing"

	testing "reconciler.io/dies/testing"
)

func TestAddressableDie_MissingMethods(t *testingx.T) {
	die := AddressableBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for AddressableDie: %s", diff.List())
	}
}

func TestConfigurationDie_MissingMethods(t *testingx.T) {
	die := ConfigurationBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ConfigurationDie: %s", diff.List())
	}
}

func TestConfigurationSpecDie_MissingMethods(t *testingx.T) {
	die := ConfigurationSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ConfigurationSpecDie: %s", diff.List())
	}
}

func TestConfigurationStatusFieldsDie_MissingMethods(t *testingx.T) {
	die := ConfigurationStatusFieldsBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ConfigurationStatusFieldsDie: %s", diff.List())
	}
}

func TestConfigurationStatusDie_MissingMethods(t *testingx.T) {
	die := ConfigurationStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ConfigurationStatusDie: %s", diff.List())
	}
}

func TestRevisionDie_MissingMethods(t *testingx.T) {
	die := RevisionBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for RevisionDie: %s", diff.List())
	}
}

func TestRevisionTemplateSpecDie_MissingMethods(t *testingx.T) {
	die := RevisionTemplateSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for RevisionTemplateSpecDie: %s", diff.List())
	}
}

func TestRevisionSpecDie_MissingMethods(t *testingx.T) {
	die := RevisionSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for RevisionSpecDie: %s", diff.List())
	}
}

func TestRevisionStatusDie_MissingMethods(t *testingx.T) {
	die := RevisionStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for RevisionStatusDie: %s", diff.List())
	}
}

func TestContainerStatusDie_MissingMethods(t *testingx.T) {
	die := ContainerStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ContainerStatusDie: %s", diff.List())
	}
}

func TestRouteDie_MissingMethods(t *testingx.T) {
	die := RouteBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for RouteDie: %s", diff.List())
	}
}

func TestTrafficTargetDie_MissingMethods(t *testingx.T) {
	die := TrafficTargetBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for TrafficTargetDie: %s", diff.List())
	}
}

func TestRouteSpecDie_MissingMethods(t *testingx.T) {
	die := RouteSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for RouteSpecDie: %s", diff.List())
	}
}

func TestRouteStatusFieldsDie_MissingMethods(t *testingx.T) {
	die := RouteStatusFieldsBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for RouteStatusFieldsDie: %s", diff.List())
	}
}

func TestRouteStatusDie_MissingMethods(t *testingx.T) {
	die := RouteStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for RouteStatusDie: %s", diff.List())
	}
}

func TestServiceDie_MissingMethods(t *testingx.T) {
	die := ServiceBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceDie: %s", diff.List())
	}
}

func TestServiceSpecDie_MissingMethods(t *testingx.T) {
	die := ServiceSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceSpecDie: %s", diff.List())
	}
}

func TestServiceStatusDie_MissingMethods(t *testingx.T) {
	die := ServiceStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceStatusDie: %s", diff.List())
	}
}
